import React, { useState } from 'react';
import { useVawayMail } from '../context/VawayMailContext';
import {
  FileCode,
  Copy,
  Check,
  Terminal,
  Settings2,
} from 'lucide-react';

export const SetupWizardView: React.FC = () => {
  const { config, updateConfig } = useVawayMail();
  const [copiedEnv, setCopiedEnv] = useState(false);
  const [copiedCompose, setCopiedCompose] = useState(false);
  const [activeTab, setActiveTab] = useState<'env' | 'compose'>('env');

  // Form options
  const [secretKey, setSecretKey] = useState(config.secret_key || 'V8L2G7L6R9T1W5Q4P0Z8N7M4X2K1J9H3');
  const [domain, setDomain] = useState(config.domain);
  const [hostname, setHostname] = useState(config.hostname);
  const [postmaster, setPostmaster] = useState(config.postmaster);
  const [tlsFlavor, setTlsFlavor] = useState(config.tls_flavor);
  const [webmail, setWebmail] = useState(config.webmail);
  const [antivirus, setAntivirus] = useState(config.antivirus ?? true);
  const [subnet, setSubnet] = useState(config.subnet || '192.168.203.0/24');
  const [compression, setCompression] = useState(config.compression || 'gz');
  const [compressionLevel, setCompressionLevel] = useState(config.compression_level || 6);
  const [realIpFrom, setRealIpFrom] = useState(config.real_ip_from || '127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16');
  const [realIpHeader, setRealIpHeader] = useState(config.real_ip_header || 'X-Forwarded-For');
  const [rejectUnlistedRecipient, setRejectUnlistedRecipient] = useState(config.reject_unlisted_recipient ?? true);
  const [relayhost, setRelayhost] = useState(config.relayhost || '');
  const [relaynets, setRelaynets] = useState(config.relaynets || '');
  const [webrootRedirect, setWebrootRedirect] = useState(config.webroot_redirect || '/webmail');

  const handleApply = (e: React.FormEvent) => {
    e.preventDefault();
    updateConfig({
      secret_key: secretKey,
      domain,
      hostname,
      postmaster,
      tls_flavor: tlsFlavor,
      webmail,
      antivirus,
      subnet,
      compression,
      compression_level: compressionLevel,
      real_ip_from: realIpFrom,
      real_ip_header: realIpHeader,
      reject_unlisted_recipient: rejectUnlistedRecipient,
      relayhost,
      relaynets,
      webroot_redirect: webrootRedirect,
    });
  };

  const generateVawayEnv = () => {
    return `# VAWAY Mail Server 2.0 configuration file
# Generated by VAWAY Admin Suite
SECRET_KEY=${secretKey}
SUBNET=${subnet}
DOMAIN=${domain}
HOSTNAMES=${hostname}
POSTMASTER=${postmaster}
TLS_FLAVOR=${tlsFlavor}
AUTH_RATELIMIT_IP=10/minute
AUTH_RATELIMIT_USER=50/minute
DISABLE_STATISTICS=False
DMARC_RUA=admin@${domain}
DMARC_RUF=admin@${domain}
MESSAGE_SIZE_LIMIT=50000000
WEBMAIL=${webmail}
ANTIVIRUS=${antivirus ? 'clamav' : 'none'}
WEB_WEBMAIL=/webmail
WEB_ADMIN=/admin
SITENAME=${config.sitename}
WEBSITE=https://${hostname}
RECAPTCHA_PUBLIC_KEY=
RECAPTCHA_PRIVATE_KEY=

# Storage Compression
COMPRESSION=${compression}
COMPRESSION_LEVEL=${compressionLevel}

# Reverse Proxy & Real IP Detection
REAL_IP_FROM=${realIpFrom}
REAL_IP_HEADER=${realIpHeader}

# Anti-Spam & Recipient Validation
REJECT_UNLISTED_RECIPIENT=${rejectUnlistedRecipient ? 'yes' : 'no'}

# Outbound SMTP Relay (Smart Host)
RELAYHOST=${relayhost}
RELAYNETS=${relaynets}

# Navigation
WEBROOT_REDIRECT=${webrootRedirect}
`;
  };

  const generateDockerCompose = () => {
    return `version: '2.2'

services:
  front:
    image: ghcr.io/vaway/nginx:2.0
    restart: always
    env_file: vaway.env
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
    volumes:
      - "/vaway/certs:/certs"
      - "/vaway/overrides/nginx:/overrides:ro"

  admin:
    image: ghcr.io/vaway/admin:2.0
    restart: always
    env_file: vaway.env
    volumes:
      - "/vaway/data:/data"
      - "/vaway/dkim:/dkim"

  imap:
    image: ghcr.io/vaway/dovecot:2.0
    restart: always
    env_file: vaway.env
    volumes:
      - "/vaway/mail:/mail"
      - "/vaway/overrides/dovecot:/overrides:ro"

  smtp:
    image: ghcr.io/vaway/postfix:2.0
    restart: always
    env_file: vaway.env
    volumes:
      - "/vaway/mailqueue:/queue"
      - "/vaway/overrides/postfix:/overrides:ro"

  antispam:
    image: ghcr.io/vaway/rspamd:2.0
    restart: always
    env_file: vaway.env
    volumes:
      - "/vaway/filter:/var/lib/rspamd"
      - "/vaway/overrides/rspamd:/overrides:ro"

${antivirus ? `  antivirus:
    image: ghcr.io/vaway/clamav:2.0
    restart: always
    env_file: vaway.env
    volumes:
      - "/vaway/filter:/data"
` : ''}
${webmail === 'roundcube' ? `  webmail:
    image: ghcr.io/vaway/webmail:2.0
    restart: always
    env_file: vaway.env
    volumes:
      - "/vaway/webmail:/data"
` : ''}`;
  };

  const copyText = (text: string, isCompose: boolean) => {
    navigator.clipboard.writeText(text);
    if (isCompose) {
      setCopiedCompose(true);
      setTimeout(() => setCopiedCompose(false), 2000);
    } else {
      setCopiedEnv(true);
      setTimeout(() => setCopiedEnv(false), 2000);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
          <FileCode className="w-5 h-5 text-sky-400" />
          VAWAY Configuration & Setup Generator
        </h1>
        <p className="text-xs text-slate-400 mt-1">
          Adjust deployment infrastructure parameters, generate production <span className="font-mono text-sky-300">vaway.env</span> and <span className="font-mono text-sky-300">docker-compose.yml</span> configurations.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Settings Form */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
          <div className="flex items-center gap-2 border-b border-slate-800 pb-3">
            <Settings2 className="w-4 h-4 text-sky-400" />
            <h2 className="text-sm font-semibold text-white">Environment Parameters</h2>
          </div>

          <form onSubmit={handleApply} className="space-y-3 text-xs">
            <div>
              <label className="block text-slate-300 font-medium mb-1">Secret Key</label>
              <input
                type="text"
                value={secretKey}
                onChange={(e) => setSecretKey(e.target.value)}
                className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 font-mono text-[11px]"
              />
            </div>

            <div>
              <label className="block text-slate-300 font-medium mb-1">Primary Domain</label>
              <input
                type="text"
                value={domain}
                onChange={(e) => setDomain(e.target.value)}
                className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 font-mono"
              />
            </div>

            <div>
              <label className="block text-slate-300 font-medium mb-1">Hostnames / FQDN</label>
              <input
                type="text"
                value={hostname}
                onChange={(e) => setHostname(e.target.value)}
                className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 font-mono"
              />
            </div>

            <div>
              <label className="block text-slate-300 font-medium mb-1">Postmaster Address</label>
              <input
                type="text"
                value={postmaster}
                onChange={(e) => setPostmaster(e.target.value)}
                className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 font-mono"
              />
            </div>

            <div>
              <label className="block text-slate-300 font-medium mb-1">TLS Flavor</label>
              <select
                value={tlsFlavor}
                onChange={(e) => setTlsFlavor(e.target.value as any)}
                className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg text-slate-200"
              >
                <option value="letsencrypt">Let's Encrypt (Automated ACME)</option>
                <option value="cert">Custom Certificate (/certs)</option>
                <option value="mail">Self-Signed Internal Certificate</option>
                <option value="notls">Reverse Proxy (No TLS termination)</option>
              </select>
            </div>

            <div>
              <label className="block text-slate-300 font-medium mb-1">Webmail Client</label>
              <select
                value={webmail}
                onChange={(e) => setWebmail(e.target.value as any)}
                className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg text-slate-200"
              >
                <option value="roundcube">Roundcube Webmail</option>
                <option value="snappy">SnappyMail</option>
                <option value="none">Disabled (IMAP/POP clients only)</option>
              </select>
            </div>

            <label className="flex items-center gap-2 text-slate-300 cursor-pointer pt-1">
              <input
                type="checkbox"
                checked={antivirus}
                onChange={(e) => setAntivirus(e.target.checked)}
                className="rounded bg-slate-800 border-slate-700 text-sky-600"
              />
              <span>Enable ClamAV Antivirus Scanning (Requires ~1.5GB RAM)</span>
            </label>

            <div>
              <label className="block text-slate-300 font-medium mb-1">Docker Subnet</label>
              <input
                type="text"
                value={subnet}
                onChange={(e) => setSubnet(e.target.value)}
                className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 font-mono"
              />
            </div>

            <div className="border-t border-slate-800 pt-3">
              <h3 className="text-slate-300 font-semibold mb-2">Storage & Performance</h3>
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block text-slate-400 text-[11px] mb-1">COMPRESSION</label>
                  <select
                    value={compression}
                    onChange={(e) => setCompression(e.target.value)}
                    className="w-full px-2.5 py-1.5 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 font-mono text-[11px]"
                  >
                    <option value="gz">gz (Gzip - Standard)</option>
                    <option value="bz2">bz2 (Bzip2)</option>
                    <option value="lz4">lz4 (Fastest)</option>
                    <option value="zstd">zstd (Modern)</option>
                    <option value="none">none (Uncompressed)</option>
                  </select>
                </div>
                <div>
                  <label className="block text-slate-400 text-[11px] mb-1">COMPRESSION_LEVEL (1-9)</label>
                  <input
                    type="number"
                    min={1}
                    max={9}
                    value={compressionLevel}
                    onChange={(e) => setCompressionLevel(Number(e.target.value))}
                    className="w-full px-2.5 py-1.5 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 font-mono text-[11px]"
                  />
                </div>
              </div>
            </div>

            <div className="border-t border-slate-800 pt-3">
              <h3 className="text-slate-300 font-semibold mb-2">Reverse Proxy & Client IP</h3>
              <div className="space-y-2">
                <div>
                  <label className="block text-slate-400 text-[11px] mb-1">REAL_IP_FROM (Trusted Subnets)</label>
                  <input
                    type="text"
                    value={realIpFrom}
                    onChange={(e) => setRealIpFrom(e.target.value)}
                    className="w-full px-2.5 py-1.5 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 font-mono text-[11px]"
                  />
                </div>
                <div>
                  <label className="block text-slate-400 text-[11px] mb-1">REAL_IP_HEADER</label>
                  <input
                    type="text"
                    value={realIpHeader}
                    onChange={(e) => setRealIpHeader(e.target.value)}
                    className="w-full px-2.5 py-1.5 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 font-mono text-[11px]"
                  />
                </div>
              </div>
            </div>

            <div className="border-t border-slate-800 pt-3">
              <h3 className="text-slate-300 font-semibold mb-2">Anti-Spam & Relay</h3>
              <label className="flex items-center gap-2 text-slate-300 cursor-pointer mb-2">
                <input
                  type="checkbox"
                  checked={rejectUnlistedRecipient}
                  onChange={(e) => setRejectUnlistedRecipient(e.target.checked)}
                  className="rounded bg-slate-800 border-slate-700 text-sky-600"
                />
                <span>REJECT_UNLISTED_RECIPIENT (Anti-Backscatter)</span>
              </label>

              <div className="space-y-2">
                <div>
                  <label className="block text-slate-400 text-[11px] mb-1">RELAYHOST (Smart Host)</label>
                  <input
                    type="text"
                    placeholder="e.g. [smtp.sendgrid.net]:587"
                    value={relayhost}
                    onChange={(e) => setRelayhost(e.target.value)}
                    className="w-full px-2.5 py-1.5 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 font-mono text-[11px]"
                  />
                </div>
                <div>
                  <label className="block text-slate-400 text-[11px] mb-1">RELAYNETS (Internal Subnets)</label>
                  <input
                    type="text"
                    placeholder="Leave empty or 127.0.0.1/32"
                    value={relaynets}
                    onChange={(e) => setRelaynets(e.target.value)}
                    className="w-full px-2.5 py-1.5 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 font-mono text-[11px]"
                  />
                </div>
                <div>
                  <label className="block text-slate-400 text-[11px] mb-1">WEBROOT_REDIRECT</label>
                  <input
                    type="text"
                    value={webrootRedirect}
                    onChange={(e) => setWebrootRedirect(e.target.value)}
                    className="w-full px-2.5 py-1.5 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 font-mono text-[11px]"
                  />
                </div>
              </div>
            </div>

            <div className="pt-2">
              <button
                type="submit"
                className="w-full py-2 bg-sky-600 hover:bg-sky-500 text-white rounded-lg font-semibold transition-colors"
              >
                Apply Parameters
              </button>
            </div>
          </form>
        </div>

        {/* Output Code Panel */}
        <div className="lg:col-span-2 bg-slate-900 border border-slate-800 rounded-xl overflow-hidden flex flex-col">
          <div className="flex items-center justify-between p-3 border-b border-slate-800 bg-slate-950/50">
            <div className="flex items-center gap-2">
              <button
                onClick={() => setActiveTab('env')}
                className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                  activeTab === 'env' ? 'bg-slate-800 text-sky-400 font-bold' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                vaway.env
              </button>
              <button
                onClick={() => setActiveTab('compose')}
                className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                  activeTab === 'compose' ? 'bg-slate-800 text-sky-400 font-bold' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                docker-compose.yml
              </button>
            </div>

            <button
              onClick={() => copyText(activeTab === 'env' ? generateVawayEnv() : generateDockerCompose(), activeTab === 'compose')}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-medium transition-colors"
            >
              {(activeTab === 'env' ? copiedEnv : copiedCompose) ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  <span className="text-emerald-400">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy Configuration</span>
                </>
              )}
            </button>
          </div>

          <pre className="p-4 flex-1 bg-slate-950 font-mono text-[11px] text-slate-300 overflow-x-auto select-all leading-relaxed">
            {activeTab === 'env' ? generateVawayEnv() : generateDockerCompose()}
          </pre>

          <div className="p-3 border-t border-slate-800 bg-slate-950/60 text-xs text-slate-400 flex items-center gap-2">
            <Terminal className="w-4 h-4 text-sky-400 shrink-0" />
            <span>Launch with: <code className="text-slate-200 font-mono">docker-compose -p vaway up -d</code></span>
          </div>
        </div>
      </div>
    </div>
  );
};
